postgres:
    docker run --name postgres12 -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:12-alpine

createdb:
    docker exec -it postgres12 createdb --username=root --owner=root bank_tx

dropdb:
    docker exec -it postgres12 dropdb bank_tx

migrateup:
    migrate -path db/migration -database "postgresql://root:secret@localhost:5432/bank_tx?sslmode=disable" -verbose up

migratedown:
    migrate -path db/migration -database "postgresql://root:secret@localhost:5432/bank_tx?sslmode=disable" -verbose down
migratedown1:
  migrate -path db/migration -database "postgresql://root:secret@localhost:5432/bank_tx?sslmode=disable" -verbose down 1
migrateup1:
  migrate -path db/migration -database "postgresql://root:secret@localhost:5432/bank_tx?sslmode=disable" -verbose up 1

proto:
	rm -f pb/*.go
	protoc --proto_path=proto --go_out=pb --go_opt=paths=source_relative \
    --go-grpc_out=pb --go-grpc_opt=paths=source_relative \
    --grpc-gateway_out=pb --grpc-gateway_opt=paths=source_relative \
    proto/*.proto

sqlc:
    sqlc generate
test:
    go test -v -cover ./...
server:
    go run main.go
evans:
    evans --host localhost --port 9090 -r repl 
    r[config host here]
redis:
	docker run --name redis -p 6379:6379 -d redis:7-alpine

.PHONY: postgres createdb dropdb migrateup migratedown sqlc test server